name = "Cart Reminder"
client_id = "2d56451600b668844beda1dc34c81926"
application_url = "https://one-cart-reminder.onrender.com"
embedded = true

[access_scopes]
scopes = "read_orders,read_customers,read_checkouts,write_marketing_events,write_draft_orders,read_draft_orders"

[auth]
redirect_urls = [
  "https://one-cart-reminder.onrender.com/auth/callback",
  "https://one-cart-reminder.onrender.com/auth/shopify/callback",
  "https://one-cart-reminder.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2026-04"

[pos]
embedded = false


[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/webhooks/orders/create"
